// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: streamer/streamer.proto

package streamer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PipelineConfig struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Method        *descriptorpb.MethodDescriptorProto `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Depth         int32                               `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"` // fork levels remaining (0 = leaf, no more forks)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineConfig) Reset() {
	*x = PipelineConfig{}
	mi := &file_streamer_streamer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineConfig) ProtoMessage() {}

func (x *PipelineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_streamer_streamer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineConfig.ProtoReflect.Descriptor instead.
func (*PipelineConfig) Descriptor() ([]byte, []int) {
	return file_streamer_streamer_proto_rawDescGZIP(), []int{0}
}

func (x *PipelineConfig) GetMethod() *descriptorpb.MethodDescriptorProto {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *PipelineConfig) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type PipelineMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*PipelineMessage_Config
	//	*PipelineMessage_Value
	Msg           isPipelineMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineMessage) Reset() {
	*x = PipelineMessage{}
	mi := &file_streamer_streamer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineMessage) ProtoMessage() {}

func (x *PipelineMessage) ProtoReflect() protoreflect.Message {
	mi := &file_streamer_streamer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineMessage.ProtoReflect.Descriptor instead.
func (*PipelineMessage) Descriptor() ([]byte, []int) {
	return file_streamer_streamer_proto_rawDescGZIP(), []int{1}
}

func (x *PipelineMessage) GetMsg() isPipelineMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *PipelineMessage) GetConfig() *PipelineConfig {
	if x != nil {
		if x, ok := x.Msg.(*PipelineMessage_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *PipelineMessage) GetValue() *anypb.Any {
	if x != nil {
		if x, ok := x.Msg.(*PipelineMessage_Value); ok {
			return x.Value
		}
	}
	return nil
}

type isPipelineMessage_Msg interface {
	isPipelineMessage_Msg()
}

type PipelineMessage_Config struct {
	Config *PipelineConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type PipelineMessage_Value struct {
	Value *anypb.Any `protobuf:"bytes,2,opt,name=value,proto3,oneof"`
}

func (*PipelineMessage_Config) isPipelineMessage_Msg() {}

func (*PipelineMessage_Value) isPipelineMessage_Msg() {}

var File_streamer_streamer_proto protoreflect.FileDescriptor

const file_streamer_streamer_proto_rawDesc = "" +
	"\n" +
	"\x17streamer/streamer.proto\x12\bstreamer\x1a\x19google/protobuf/any.proto\x1a google/protobuf/descriptor.proto\"f\n" +
	"\x0ePipelineConfig\x12>\n" +
	"\x06method\x18\x01 \x01(\v2&.google.protobuf.MethodDescriptorProtoR\x06method\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"z\n" +
	"\x0fPipelineMessage\x122\n" +
	"\x06config\x18\x01 \x01(\v2\x18.streamer.PipelineConfigH\x00R\x06config\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyH\x00R\x05valueB\x05\n" +
	"\x03msg2\x89\x01\n" +
	"\bStreamer\x127\n" +
	"\tIncrement\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\x12D\n" +
	"\bPipeline\x12\x19.streamer.PipelineMessage\x1a\x19.streamer.PipelineMessage(\x010\x01B(Z&github.com/accretional/runrpc/streamerb\x06proto3"

var (
	file_streamer_streamer_proto_rawDescOnce sync.Once
	file_streamer_streamer_proto_rawDescData []byte
)

func file_streamer_streamer_proto_rawDescGZIP() []byte {
	file_streamer_streamer_proto_rawDescOnce.Do(func() {
		file_streamer_streamer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamer_streamer_proto_rawDesc), len(file_streamer_streamer_proto_rawDesc)))
	})
	return file_streamer_streamer_proto_rawDescData
}

var file_streamer_streamer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_streamer_streamer_proto_goTypes = []any{
	(*PipelineConfig)(nil),                     // 0: streamer.PipelineConfig
	(*PipelineMessage)(nil),                    // 1: streamer.PipelineMessage
	(*descriptorpb.MethodDescriptorProto)(nil), // 2: google.protobuf.MethodDescriptorProto
	(*anypb.Any)(nil),                          // 3: google.protobuf.Any
}
var file_streamer_streamer_proto_depIdxs = []int32{
	2, // 0: streamer.PipelineConfig.method:type_name -> google.protobuf.MethodDescriptorProto
	0, // 1: streamer.PipelineMessage.config:type_name -> streamer.PipelineConfig
	3, // 2: streamer.PipelineMessage.value:type_name -> google.protobuf.Any
	3, // 3: streamer.Streamer.Increment:input_type -> google.protobuf.Any
	1, // 4: streamer.Streamer.Pipeline:input_type -> streamer.PipelineMessage
	3, // 5: streamer.Streamer.Increment:output_type -> google.protobuf.Any
	1, // 6: streamer.Streamer.Pipeline:output_type -> streamer.PipelineMessage
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_streamer_streamer_proto_init() }
func file_streamer_streamer_proto_init() {
	if File_streamer_streamer_proto != nil {
		return
	}
	file_streamer_streamer_proto_msgTypes[1].OneofWrappers = []any{
		(*PipelineMessage_Config)(nil),
		(*PipelineMessage_Value)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamer_streamer_proto_rawDesc), len(file_streamer_streamer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streamer_streamer_proto_goTypes,
		DependencyIndexes: file_streamer_streamer_proto_depIdxs,
		MessageInfos:      file_streamer_streamer_proto_msgTypes,
	}.Build()
	File_streamer_streamer_proto = out.File
	file_streamer_streamer_proto_goTypes = nil
	file_streamer_streamer_proto_depIdxs = nil
}
