// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: identifier/identifier.proto

package identifier

import (
	context "context"
	filer "github.com/accretional/runrpc/filer"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Identifier_Authenticate_FullMethodName = "/identifier.Identifier/Authenticate"
	Identifier_Authority_FullMethodName    = "/identifier.Identifier/Authority"
	Identifier_Identify_FullMethodName     = "/identifier.Identifier/Identify"
)

// IdentifierClient is the client API for Identifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentifierClient interface {
	// If successful, ultimately returns a resource with a token inside of it owned by the authenticated user, with resource info for Identity.name (eg a user, or group, etc) embedded
	// Those help inform the resource targets of a subsequent Plan92.CreateSession (authorization)
	// Before then, an auth flow may be required
	Authenticate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Identity, filer.Resource], error)
	// Determine if the resource of this name belongs to this server, and if so, its local identity, if not, a remote authority
	Authority(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*Identity, error)
	// Request the identity of the owner of this resource
	// Can also be used to check the identity of this service/identity provider, by asking about "system"/id=0
	Identify(ctx context.Context, in *filer.Resource, opts ...grpc.CallOption) (*Identity, error)
}

type identifierClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentifierClient(cc grpc.ClientConnInterface) IdentifierClient {
	return &identifierClient{cc}
}

func (c *identifierClient) Authenticate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Identity, filer.Resource], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Identifier_ServiceDesc.Streams[0], Identifier_Authenticate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Identity, filer.Resource]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Identifier_AuthenticateClient = grpc.BidiStreamingClient[Identity, filer.Resource]

func (c *identifierClient) Authority(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*Identity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Identity)
	err := c.cc.Invoke(ctx, Identifier_Authority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identifierClient) Identify(ctx context.Context, in *filer.Resource, opts ...grpc.CallOption) (*Identity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Identity)
	err := c.cc.Invoke(ctx, Identifier_Identify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentifierServer is the server API for Identifier service.
// All implementations must embed UnimplementedIdentifierServer
// for forward compatibility.
type IdentifierServer interface {
	// If successful, ultimately returns a resource with a token inside of it owned by the authenticated user, with resource info for Identity.name (eg a user, or group, etc) embedded
	// Those help inform the resource targets of a subsequent Plan92.CreateSession (authorization)
	// Before then, an auth flow may be required
	Authenticate(grpc.BidiStreamingServer[Identity, filer.Resource]) error
	// Determine if the resource of this name belongs to this server, and if so, its local identity, if not, a remote authority
	Authority(context.Context, *Identity) (*Identity, error)
	// Request the identity of the owner of this resource
	// Can also be used to check the identity of this service/identity provider, by asking about "system"/id=0
	Identify(context.Context, *filer.Resource) (*Identity, error)
	mustEmbedUnimplementedIdentifierServer()
}

// UnimplementedIdentifierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentifierServer struct{}

func (UnimplementedIdentifierServer) Authenticate(grpc.BidiStreamingServer[Identity, filer.Resource]) error {
	return status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedIdentifierServer) Authority(context.Context, *Identity) (*Identity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authority not implemented")
}
func (UnimplementedIdentifierServer) Identify(context.Context, *filer.Resource) (*Identity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Identify not implemented")
}
func (UnimplementedIdentifierServer) mustEmbedUnimplementedIdentifierServer() {}
func (UnimplementedIdentifierServer) testEmbeddedByValue()                    {}

// UnsafeIdentifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentifierServer will
// result in compilation errors.
type UnsafeIdentifierServer interface {
	mustEmbedUnimplementedIdentifierServer()
}

func RegisterIdentifierServer(s grpc.ServiceRegistrar, srv IdentifierServer) {
	// If the following call pancis, it indicates UnimplementedIdentifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Identifier_ServiceDesc, srv)
}

func _Identifier_Authenticate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IdentifierServer).Authenticate(&grpc.GenericServerStream[Identity, filer.Resource]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Identifier_AuthenticateServer = grpc.BidiStreamingServer[Identity, filer.Resource]

func _Identifier_Authority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentifierServer).Authority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identifier_Authority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentifierServer).Authority(ctx, req.(*Identity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identifier_Identify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(filer.Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentifierServer).Identify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identifier_Identify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentifierServer).Identify(ctx, req.(*filer.Resource))
	}
	return interceptor(ctx, in, info, handler)
}

// Identifier_ServiceDesc is the grpc.ServiceDesc for Identifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Identifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identifier.Identifier",
	HandlerType: (*IdentifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authority",
			Handler:    _Identifier_Authority_Handler,
		},
		{
			MethodName: "Identify",
			Handler:    _Identifier_Identify_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Authenticate",
			Handler:       _Identifier_Authenticate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "identifier/identifier.proto",
}
