// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: identifier/identifier.proto

package identifier

import (
	filer "github.com/accretional/runrpc/filer"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Identity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity name according to the provider
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Local identity the user wishes to authenticate as here. Can be the same as id
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Provider:
	//
	//	*Identity_LocalAuthority
	//	*Identity_RemoteAuthority
	//	*Identity_Secret
	Provider      isIdentity_Provider `protobuf_oneof:"provider"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_identifier_identifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_identifier_identifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_identifier_identifier_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Identity) GetProvider() isIdentity_Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *Identity) GetLocalAuthority() *Identity {
	if x != nil {
		if x, ok := x.Provider.(*Identity_LocalAuthority); ok {
			return x.LocalAuthority
		}
	}
	return nil
}

func (x *Identity) GetRemoteAuthority() *Identity {
	if x != nil {
		if x, ok := x.Provider.(*Identity_RemoteAuthority); ok {
			return x.RemoteAuthority
		}
	}
	return nil
}

func (x *Identity) GetSecret() string {
	if x != nil {
		if x, ok := x.Provider.(*Identity_Secret); ok {
			return x.Secret
		}
	}
	return ""
}

type isIdentity_Provider interface {
	isIdentity_Provider()
}

type Identity_LocalAuthority struct {
	LocalAuthority *Identity `protobuf:"bytes,3,opt,name=local_authority,json=localAuthority,proto3,oneof"`
}

type Identity_RemoteAuthority struct {
	RemoteAuthority *Identity `protobuf:"bytes,4,opt,name=remote_authority,json=remoteAuthority,proto3,oneof"`
}

type Identity_Secret struct {
	Secret string `protobuf:"bytes,5,opt,name=secret,proto3,oneof"`
}

func (*Identity_LocalAuthority) isIdentity_Provider() {}

func (*Identity_RemoteAuthority) isIdentity_Provider() {}

func (*Identity_Secret) isIdentity_Provider() {}

var File_identifier_identifier_proto protoreflect.FileDescriptor

const file_identifier_identifier_proto_rawDesc = "" +
	"\n" +
	"\x1bidentifier/identifier.proto\x12\n" +
	"identifier\x1a\x12filer/plan92.proto\"\xd8\x01\n" +
	"\bIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12?\n" +
	"\x0flocal_authority\x18\x03 \x01(\v2\x14.identifier.IdentityH\x00R\x0elocalAuthority\x12A\n" +
	"\x10remote_authority\x18\x04 \x01(\v2\x14.identifier.IdentityH\x00R\x0fremoteAuthority\x12\x18\n" +
	"\x06secret\x18\x05 \x01(\tH\x00R\x06secretB\n" +
	"\n" +
	"\bprovider2\xb3\x01\n" +
	"\n" +
	"Identifier\x129\n" +
	"\fAuthenticate\x12\x14.identifier.Identity\x1a\x0f.filer.Resource(\x010\x01\x127\n" +
	"\tAuthority\x12\x14.identifier.Identity\x1a\x14.identifier.Identity\x121\n" +
	"\bIdentify\x12\x0f.filer.Resource\x1a\x14.identifier.IdentityB*Z(github.com/accretional/runrpc/identifierb\x06proto3"

var (
	file_identifier_identifier_proto_rawDescOnce sync.Once
	file_identifier_identifier_proto_rawDescData []byte
)

func file_identifier_identifier_proto_rawDescGZIP() []byte {
	file_identifier_identifier_proto_rawDescOnce.Do(func() {
		file_identifier_identifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identifier_identifier_proto_rawDesc), len(file_identifier_identifier_proto_rawDesc)))
	})
	return file_identifier_identifier_proto_rawDescData
}

var file_identifier_identifier_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_identifier_identifier_proto_goTypes = []any{
	(*Identity)(nil),       // 0: identifier.Identity
	(*filer.Resource)(nil), // 1: filer.Resource
}
var file_identifier_identifier_proto_depIdxs = []int32{
	0, // 0: identifier.Identity.local_authority:type_name -> identifier.Identity
	0, // 1: identifier.Identity.remote_authority:type_name -> identifier.Identity
	0, // 2: identifier.Identifier.Authenticate:input_type -> identifier.Identity
	0, // 3: identifier.Identifier.Authority:input_type -> identifier.Identity
	1, // 4: identifier.Identifier.Identify:input_type -> filer.Resource
	1, // 5: identifier.Identifier.Authenticate:output_type -> filer.Resource
	0, // 6: identifier.Identifier.Authority:output_type -> identifier.Identity
	0, // 7: identifier.Identifier.Identify:output_type -> identifier.Identity
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_identifier_identifier_proto_init() }
func file_identifier_identifier_proto_init() {
	if File_identifier_identifier_proto != nil {
		return
	}
	file_identifier_identifier_proto_msgTypes[0].OneofWrappers = []any{
		(*Identity_LocalAuthority)(nil),
		(*Identity_RemoteAuthority)(nil),
		(*Identity_Secret)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identifier_identifier_proto_rawDesc), len(file_identifier_identifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identifier_identifier_proto_goTypes,
		DependencyIndexes: file_identifier_identifier_proto_depIdxs,
		MessageInfos:      file_identifier_identifier_proto_msgTypes,
	}.Build()
	File_identifier_identifier_proto = out.File
	file_identifier_identifier_proto_goTypes = nil
	file_identifier_identifier_proto_depIdxs = nil
}
