// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: loader/loader.proto

package loader

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Loader_Exec_FullMethodName = "/loader.Loader/Exec"
	Loader_Link_FullMethodName = "/loader.Loader/Link"
	Loader_Load_FullMethodName = "/loader.Loader/Load"
)

// LoaderClient is the client API for Loader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Loader service handles loading of binaries
type LoaderClient interface {
	// Exec implements execve(const char *pathname, char *const argv[], char *const envp[]):
	Exec(ctx context.Context, in *ExecutionArgs, opts ...grpc.CallOption) (*ExitCode, error)
	// Link is like ~dlopen but in a way that allows for deferred Loading
	Link(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BytesValue, LoadHandle], error)
	// Load implements fexecve
	Load(ctx context.Context, in *LoadArgs, opts ...grpc.CallOption) (*ExitCode, error)
}

type loaderClient struct {
	cc grpc.ClientConnInterface
}

func NewLoaderClient(cc grpc.ClientConnInterface) LoaderClient {
	return &loaderClient{cc}
}

func (c *loaderClient) Exec(ctx context.Context, in *ExecutionArgs, opts ...grpc.CallOption) (*ExitCode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExitCode)
	err := c.cc.Invoke(ctx, Loader_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loaderClient) Link(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BytesValue, LoadHandle], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Loader_ServiceDesc.Streams[0], Loader_Link_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BytesValue, LoadHandle]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Loader_LinkClient = grpc.ClientStreamingClient[BytesValue, LoadHandle]

func (c *loaderClient) Load(ctx context.Context, in *LoadArgs, opts ...grpc.CallOption) (*ExitCode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExitCode)
	err := c.cc.Invoke(ctx, Loader_Load_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoaderServer is the server API for Loader service.
// All implementations must embed UnimplementedLoaderServer
// for forward compatibility.
//
// Loader service handles loading of binaries
type LoaderServer interface {
	// Exec implements execve(const char *pathname, char *const argv[], char *const envp[]):
	Exec(context.Context, *ExecutionArgs) (*ExitCode, error)
	// Link is like ~dlopen but in a way that allows for deferred Loading
	Link(grpc.ClientStreamingServer[BytesValue, LoadHandle]) error
	// Load implements fexecve
	Load(context.Context, *LoadArgs) (*ExitCode, error)
	mustEmbedUnimplementedLoaderServer()
}

// UnimplementedLoaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoaderServer struct{}

func (UnimplementedLoaderServer) Exec(context.Context, *ExecutionArgs) (*ExitCode, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedLoaderServer) Link(grpc.ClientStreamingServer[BytesValue, LoadHandle]) error {
	return status.Error(codes.Unimplemented, "method Link not implemented")
}
func (UnimplementedLoaderServer) Load(context.Context, *LoadArgs) (*ExitCode, error) {
	return nil, status.Error(codes.Unimplemented, "method Load not implemented")
}
func (UnimplementedLoaderServer) mustEmbedUnimplementedLoaderServer() {}
func (UnimplementedLoaderServer) testEmbeddedByValue()                {}

// UnsafeLoaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoaderServer will
// result in compilation errors.
type UnsafeLoaderServer interface {
	mustEmbedUnimplementedLoaderServer()
}

func RegisterLoaderServer(s grpc.ServiceRegistrar, srv LoaderServer) {
	// If the following call panics, it indicates UnimplementedLoaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Loader_ServiceDesc, srv)
}

func _Loader_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoaderServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Loader_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoaderServer).Exec(ctx, req.(*ExecutionArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Loader_Link_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LoaderServer).Link(&grpc.GenericServerStream[BytesValue, LoadHandle]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Loader_LinkServer = grpc.ClientStreamingServer[BytesValue, LoadHandle]

func _Loader_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoaderServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Loader_Load_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoaderServer).Load(ctx, req.(*LoadArgs))
	}
	return interceptor(ctx, in, info, handler)
}

// Loader_ServiceDesc is the grpc.ServiceDesc for Loader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Loader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loader.Loader",
	HandlerType: (*LoaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exec",
			Handler:    _Loader_Exec_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _Loader_Load_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Link",
			Handler:       _Loader_Link_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "loader/loader.proto",
}
