// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: loader/loader.proto

package loader

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BytesValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytesValue) Reset() {
	*x = BytesValue{}
	mi := &file_loader_loader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesValue) ProtoMessage() {}

func (x *BytesValue) ProtoReflect() protoreflect.Message {
	mi := &file_loader_loader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesValue.ProtoReflect.Descriptor instead.
func (*BytesValue) Descriptor() ([]byte, []int) {
	return file_loader_loader_proto_rawDescGZIP(), []int{0}
}

func (x *BytesValue) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecutionArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionArgs) Reset() {
	*x = ExecutionArgs{}
	mi := &file_loader_loader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionArgs) ProtoMessage() {}

func (x *ExecutionArgs) ProtoReflect() protoreflect.Message {
	mi := &file_loader_loader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionArgs.ProtoReflect.Descriptor instead.
func (*ExecutionArgs) Descriptor() ([]byte, []int) {
	return file_loader_loader_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionArgs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExecutionArgs) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecutionArgs) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type LoadArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadArgs) Reset() {
	*x = LoadArgs{}
	mi := &file_loader_loader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadArgs) ProtoMessage() {}

func (x *LoadArgs) ProtoReflect() protoreflect.Message {
	mi := &file_loader_loader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadArgs.ProtoReflect.Descriptor instead.
func (*LoadArgs) Descriptor() ([]byte, []int) {
	return file_loader_loader_proto_rawDescGZIP(), []int{2}
}

func (x *LoadArgs) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *LoadArgs) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *LoadArgs) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ExitCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitCode) Reset() {
	*x = ExitCode{}
	mi := &file_loader_loader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitCode) ProtoMessage() {}

func (x *ExitCode) ProtoReflect() protoreflect.Message {
	mi := &file_loader_loader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitCode.ProtoReflect.Descriptor instead.
func (*ExitCode) Descriptor() ([]byte, []int) {
	return file_loader_loader_proto_rawDescGZIP(), []int{3}
}

func (x *ExitCode) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type LoadHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadHandle) Reset() {
	*x = LoadHandle{}
	mi := &file_loader_loader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadHandle) ProtoMessage() {}

func (x *LoadHandle) ProtoReflect() protoreflect.Message {
	mi := &file_loader_loader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadHandle.ProtoReflect.Descriptor instead.
func (*LoadHandle) Descriptor() ([]byte, []int) {
	return file_loader_loader_proto_rawDescGZIP(), []int{4}
}

func (x *LoadHandle) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

var File_loader_loader_proto protoreflect.FileDescriptor

const file_loader_loader_proto_rawDesc = "" +
	"\n" +
	"\x13loader/loader.proto\x12\x06loader\" \n" +
	"\n" +
	"BytesValue\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xa1\x01\n" +
	"\rExecutionArgs\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x120\n" +
	"\x03env\x18\x03 \x03(\v2\x1e.loader.ExecutionArgs.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\bLoadArgs\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12+\n" +
	"\x03env\x18\x03 \x03(\v2\x19.loader.LoadArgs.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1e\n" +
	"\bExitCode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\"\x1c\n" +
	"\n" +
	"LoadHandle\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd2\x97\x01\n" +
	"\x06Loader\x12/\n" +
	"\x04Exec\x12\x15.loader.ExecutionArgs\x1a\x10.loader.ExitCode\x120\n" +
	"\x04Link\x12\x12.loader.BytesValue\x1a\x12.loader.LoadHandle(\x01\x12*\n" +
	"\x04Load\x12\x10.loader.LoadArgs\x1a\x10.loader.ExitCodeB&Z$github.com/accretional/runrpc/loaderb\x06proto3"

var (
	file_loader_loader_proto_rawDescOnce sync.Once
	file_loader_loader_proto_rawDescData []byte
)

func file_loader_loader_proto_rawDescGZIP() []byte {
	file_loader_loader_proto_rawDescOnce.Do(func() {
		file_loader_loader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loader_loader_proto_rawDesc), len(file_loader_loader_proto_rawDesc)))
	})
	return file_loader_loader_proto_rawDescData
}

var file_loader_loader_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_loader_loader_proto_goTypes = []any{
	(*BytesValue)(nil),    // 0: loader.BytesValue
	(*ExecutionArgs)(nil), // 1: loader.ExecutionArgs
	(*LoadArgs)(nil),      // 2: loader.LoadArgs
	(*ExitCode)(nil),      // 3: loader.ExitCode
	(*LoadHandle)(nil),    // 4: loader.LoadHandle
	nil,                   // 5: loader.ExecutionArgs.EnvEntry
	nil,                   // 6: loader.LoadArgs.EnvEntry
}
var file_loader_loader_proto_depIdxs = []int32{
	5, // 0: loader.ExecutionArgs.env:type_name -> loader.ExecutionArgs.EnvEntry
	6, // 1: loader.LoadArgs.env:type_name -> loader.LoadArgs.EnvEntry
	1, // 2: loader.Loader.Exec:input_type -> loader.ExecutionArgs
	0, // 3: loader.Loader.Link:input_type -> loader.BytesValue
	2, // 4: loader.Loader.Load:input_type -> loader.LoadArgs
	3, // 5: loader.Loader.Exec:output_type -> loader.ExitCode
	4, // 6: loader.Loader.Link:output_type -> loader.LoadHandle
	3, // 7: loader.Loader.Load:output_type -> loader.ExitCode
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_loader_loader_proto_init() }
func file_loader_loader_proto_init() {
	if File_loader_loader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loader_loader_proto_rawDesc), len(file_loader_loader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loader_loader_proto_goTypes,
		DependencyIndexes: file_loader_loader_proto_depIdxs,
		MessageInfos:      file_loader_loader_proto_msgTypes,
	}.Build()
	File_loader_loader_proto = out.File
	file_loader_loader_proto_goTypes = nil
	file_loader_loader_proto_depIdxs = nil
}
