// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: images/images.proto

package images

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Local file path or remote URL (http/https).
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Desired ASCII art width in characters. 0 = auto (fit terminal).
	Width int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	// Desired ASCII art height in characters. 0 = auto (derive from width).
	Height int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// For videos/GIFs: frames per second to extract. 0 = default (10).
	Fps int32 `protobuf:"varint,4,opt,name=fps,proto3" json:"fps,omitempty"`
	// For videos/GIFs: max duration in seconds to process. 0 = all.
	MaxSeconds float32 `protobuf:"fixed32,5,opt,name=max_seconds,json=maxSeconds,proto3" json:"max_seconds,omitempty"`
	// Use color ANSI output. Default true.
	Color bool `protobuf:"varint,6,opt,name=color,proto3" json:"color,omitempty"`
	// Invert brightness.
	Invert        bool `protobuf:"varint,7,opt,name=invert,proto3" json:"invert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_images_images_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_images_images_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_images_images_proto_rawDescGZIP(), []int{0}
}

func (x *RenderRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RenderRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RenderRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RenderRequest) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *RenderRequest) GetMaxSeconds() float32 {
	if x != nil {
		return x.MaxSeconds
	}
	return 0
}

func (x *RenderRequest) GetColor() bool {
	if x != nil {
		return x.Color
	}
	return false
}

func (x *RenderRequest) GetInvert() bool {
	if x != nil {
		return x.Invert
	}
	return false
}

type RenderBytesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw file contents.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// File extension hint (e.g. ".webm", ".gif", ".png") so we know
	// how to decode it.
	Format string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	// Same options as RenderRequest.
	Width         int32   `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32   `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Fps           int32   `protobuf:"varint,5,opt,name=fps,proto3" json:"fps,omitempty"`
	MaxSeconds    float32 `protobuf:"fixed32,6,opt,name=max_seconds,json=maxSeconds,proto3" json:"max_seconds,omitempty"`
	Color         bool    `protobuf:"varint,7,opt,name=color,proto3" json:"color,omitempty"`
	Invert        bool    `protobuf:"varint,8,opt,name=invert,proto3" json:"invert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderBytesRequest) Reset() {
	*x = RenderBytesRequest{}
	mi := &file_images_images_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderBytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderBytesRequest) ProtoMessage() {}

func (x *RenderBytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_images_images_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderBytesRequest.ProtoReflect.Descriptor instead.
func (*RenderBytesRequest) Descriptor() ([]byte, []int) {
	return file_images_images_proto_rawDescGZIP(), []int{1}
}

func (x *RenderBytesRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RenderBytesRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RenderBytesRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RenderBytesRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RenderBytesRequest) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *RenderBytesRequest) GetMaxSeconds() float32 {
	if x != nil {
		return x.MaxSeconds
	}
	return 0
}

func (x *RenderBytesRequest) GetColor() bool {
	if x != nil {
		return x.Color
	}
	return false
}

func (x *RenderBytesRequest) GetInvert() bool {
	if x != nil {
		return x.Invert
	}
	return false
}

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ASCII art for this frame, including ANSI color codes if requested.
	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Frame index (0-based).
	Index int32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// Total number of frames (may be 1 for static images).
	Total         int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_images_images_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_images_images_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_images_images_proto_rawDescGZIP(), []int{2}
}

func (x *Frame) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Frame) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Frame) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_images_images_proto protoreflect.FileDescriptor

const file_images_images_proto_rawDesc = "" +
	"\n" +
	"\x13images/images.proto\x12\x06images\"\xb6\x01\n" +
	"\rRenderRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x10\n" +
	"\x03fps\x18\x04 \x01(\x05R\x03fps\x12\x1f\n" +
	"\vmax_seconds\x18\x05 \x01(\x02R\n" +
	"maxSeconds\x12\x14\n" +
	"\x05color\x18\x06 \x01(\bR\x05color\x12\x16\n" +
	"\x06invert\x18\a \x01(\bR\x06invert\"\xcf\x01\n" +
	"\x12RenderBytesRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x10\n" +
	"\x03fps\x18\x05 \x01(\x05R\x03fps\x12\x1f\n" +
	"\vmax_seconds\x18\x06 \x01(\x02R\n" +
	"maxSeconds\x12\x14\n" +
	"\x05color\x18\a \x01(\bR\x05color\x12\x16\n" +
	"\x06invert\x18\b \x01(\bR\x06invert\"G\n" +
	"\x05Frame\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total2v\n" +
	"\x06Imager\x120\n" +
	"\x06Render\x12\x15.images.RenderRequest\x1a\r.images.Frame0\x01\x12:\n" +
	"\vRenderBytes\x12\x1a.images.RenderBytesRequest\x1a\r.images.Frame0\x01B&Z$github.com/accretional/runrpc/imagesb\x06proto3"

var (
	file_images_images_proto_rawDescOnce sync.Once
	file_images_images_proto_rawDescData []byte
)

func file_images_images_proto_rawDescGZIP() []byte {
	file_images_images_proto_rawDescOnce.Do(func() {
		file_images_images_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_images_images_proto_rawDesc), len(file_images_images_proto_rawDesc)))
	})
	return file_images_images_proto_rawDescData
}

var file_images_images_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_images_images_proto_goTypes = []any{
	(*RenderRequest)(nil),      // 0: images.RenderRequest
	(*RenderBytesRequest)(nil), // 1: images.RenderBytesRequest
	(*Frame)(nil),              // 2: images.Frame
}
var file_images_images_proto_depIdxs = []int32{
	0, // 0: images.Imager.Render:input_type -> images.RenderRequest
	1, // 1: images.Imager.RenderBytes:input_type -> images.RenderBytesRequest
	2, // 2: images.Imager.Render:output_type -> images.Frame
	2, // 3: images.Imager.RenderBytes:output_type -> images.Frame
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_images_images_proto_init() }
func file_images_images_proto_init() {
	if File_images_images_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_images_images_proto_rawDesc), len(file_images_images_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_images_images_proto_goTypes,
		DependencyIndexes: file_images_images_proto_depIdxs,
		MessageInfos:      file_images_images_proto_msgTypes,
	}.Build()
	File_images_images_proto = out.File
	file_images_images_proto_goTypes = nil
	file_images_images_proto_depIdxs = nil
}
