// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: images/images.proto

package images

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Imager_Render_FullMethodName      = "/images.Imager/Render"
	Imager_RenderBytes_FullMethodName = "/images.Imager/RenderBytes"
)

// ImagerClient is the client API for Imager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Imager converts images, GIFs, videos (webm/mp4), and webp files
// into colored ASCII art frames.
type ImagerClient interface {
	// Render takes a local path or remote URL to an image/video and
	// returns a stream of ASCII art frames.
	Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Frame], error)
	// RenderBytes accepts raw file bytes (for when the caller already
	// has the data) and returns ASCII art frames.
	RenderBytes(ctx context.Context, in *RenderBytesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Frame], error)
}

type imagerClient struct {
	cc grpc.ClientConnInterface
}

func NewImagerClient(cc grpc.ClientConnInterface) ImagerClient {
	return &imagerClient{cc}
}

func (c *imagerClient) Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Imager_ServiceDesc.Streams[0], Imager_Render_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RenderRequest, Frame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Imager_RenderClient = grpc.ServerStreamingClient[Frame]

func (c *imagerClient) RenderBytes(ctx context.Context, in *RenderBytesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Imager_ServiceDesc.Streams[1], Imager_RenderBytes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RenderBytesRequest, Frame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Imager_RenderBytesClient = grpc.ServerStreamingClient[Frame]

// ImagerServer is the server API for Imager service.
// All implementations must embed UnimplementedImagerServer
// for forward compatibility.
//
// Imager converts images, GIFs, videos (webm/mp4), and webp files
// into colored ASCII art frames.
type ImagerServer interface {
	// Render takes a local path or remote URL to an image/video and
	// returns a stream of ASCII art frames.
	Render(*RenderRequest, grpc.ServerStreamingServer[Frame]) error
	// RenderBytes accepts raw file bytes (for when the caller already
	// has the data) and returns ASCII art frames.
	RenderBytes(*RenderBytesRequest, grpc.ServerStreamingServer[Frame]) error
	mustEmbedUnimplementedImagerServer()
}

// UnimplementedImagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImagerServer struct{}

func (UnimplementedImagerServer) Render(*RenderRequest, grpc.ServerStreamingServer[Frame]) error {
	return status.Errorf(codes.Unimplemented, "method Render not implemented")
}
func (UnimplementedImagerServer) RenderBytes(*RenderBytesRequest, grpc.ServerStreamingServer[Frame]) error {
	return status.Errorf(codes.Unimplemented, "method RenderBytes not implemented")
}
func (UnimplementedImagerServer) mustEmbedUnimplementedImagerServer() {}
func (UnimplementedImagerServer) testEmbeddedByValue()                {}

// UnsafeImagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImagerServer will
// result in compilation errors.
type UnsafeImagerServer interface {
	mustEmbedUnimplementedImagerServer()
}

func RegisterImagerServer(s grpc.ServiceRegistrar, srv ImagerServer) {
	// If the following call pancis, it indicates UnimplementedImagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Imager_ServiceDesc, srv)
}

func _Imager_Render_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RenderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImagerServer).Render(m, &grpc.GenericServerStream[RenderRequest, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Imager_RenderServer = grpc.ServerStreamingServer[Frame]

func _Imager_RenderBytes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RenderBytesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImagerServer).RenderBytes(m, &grpc.GenericServerStream[RenderBytesRequest, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Imager_RenderBytesServer = grpc.ServerStreamingServer[Frame]

// Imager_ServiceDesc is the grpc.ServiceDesc for Imager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Imager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "images.Imager",
	HandlerType: (*ImagerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Render",
			Handler:       _Imager_Render_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RenderBytes",
			Handler:       _Imager_RenderBytes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "images/images.proto",
}
