// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: commander/commander.proto

package commander

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The command to execute (can include shell syntax)
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Arguments to pass to the command
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// Working directory
	WorkingDir string `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// Environment variables
	Env map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Timeout in seconds (0 = no timeout)
	TimeoutSeconds int32 `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Shell to use (e.g., /bin/sh, /bin/bash)
	Shell         string `protobuf:"bytes,6,opt,name=shell,proto3" json:"shell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_commander_commander_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_commander_commander_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_commander_commander_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *Command) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Command) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Command) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

type Output struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// else stderr
	Stdout        bool   `protobuf:"varint,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_commander_commander_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_commander_commander_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_commander_commander_proto_rawDescGZIP(), []int{1}
}

func (x *Output) GetStdout() bool {
	if x != nil {
		return x.Stdout
	}
	return false
}

func (x *Output) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_commander_commander_proto protoreflect.FileDescriptor

const file_commander_commander_proto_rawDesc = "" +
	"\n" +
	"\x19commander/commander.proto\x12\tcommander\"\xfe\x01\n" +
	"\aCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12-\n" +
	"\x03env\x18\x04 \x03(\v2\x1b.commander.Command.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x14\n" +
	"\x05shell\x18\x06 \x01(\tR\x05shell\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x06Output\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\bR\x06stdout\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2=\n" +
	"\tCommander\x120\n" +
	"\x05Shell\x12\x12.commander.Command\x1a\x11.commander.Output0\x01B)Z'github.com/accretional/runrpc/commanderb\x06proto3"

var (
	file_commander_commander_proto_rawDescOnce sync.Once
	file_commander_commander_proto_rawDescData []byte
)

func file_commander_commander_proto_rawDescGZIP() []byte {
	file_commander_commander_proto_rawDescOnce.Do(func() {
		file_commander_commander_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commander_commander_proto_rawDesc), len(file_commander_commander_proto_rawDesc)))
	})
	return file_commander_commander_proto_rawDescData
}

var file_commander_commander_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_commander_commander_proto_goTypes = []any{
	(*Command)(nil), // 0: commander.Command
	(*Output)(nil),  // 1: commander.Output
	nil,             // 2: commander.Command.EnvEntry
}
var file_commander_commander_proto_depIdxs = []int32{
	2, // 0: commander.Command.env:type_name -> commander.Command.EnvEntry
	0, // 1: commander.Commander.Shell:input_type -> commander.Command
	1, // 2: commander.Commander.Shell:output_type -> commander.Output
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_commander_commander_proto_init() }
func file_commander_commander_proto_init() {
	if File_commander_commander_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commander_commander_proto_rawDesc), len(file_commander_commander_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_commander_commander_proto_goTypes,
		DependencyIndexes: file_commander_commander_proto_depIdxs,
		MessageInfos:      file_commander_commander_proto_msgTypes,
	}.Build()
	File_commander_commander_proto = out.File
	file_commander_commander_proto_goTypes = nil
	file_commander_commander_proto_depIdxs = nil
}
