// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: runner/runner.proto

package runner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TODO: we should cleanup/remove these and also check the way we are encoding them
// actually matches the attrp object.
type PosixSpawnFlag int32

const (
	// Proto3 requires the first enum value to be 0.
	PosixSpawnFlag_POSIX_SPAWN_UNKNOWN PosixSpawnFlag = 0
)

// Enum value maps for PosixSpawnFlag.
var (
	PosixSpawnFlag_name = map[int32]string{
		0: "POSIX_SPAWN_UNKNOWN",
	}
	PosixSpawnFlag_value = map[string]int32{
		"POSIX_SPAWN_UNKNOWN": 0,
	}
)

func (x PosixSpawnFlag) Enum() *PosixSpawnFlag {
	p := new(PosixSpawnFlag)
	*p = x
	return p
}

func (x PosixSpawnFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PosixSpawnFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_runner_runner_proto_enumTypes[0].Descriptor()
}

func (PosixSpawnFlag) Type() protoreflect.EnumType {
	return &file_runner_runner_proto_enumTypes[0]
}

func (x PosixSpawnFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PosixSpawnFlag.Descriptor instead.
func (PosixSpawnFlag) EnumDescriptor() ([]byte, []int) {
	return file_runner_runner_proto_rawDescGZIP(), []int{0}
}

type FileActionKind int32

const (
	FileActionKind_FILEACTIONUNKNOWN FileActionKind = 0
	FileActionKind_FILEACTIONOPEN    FileActionKind = 1
	FileActionKind_FILEACTIONCLOSE   FileActionKind = 2
	FileActionKind_FILEACTIONDUP     FileActionKind = 3
)

// Enum value maps for FileActionKind.
var (
	FileActionKind_name = map[int32]string{
		0: "FILEACTIONUNKNOWN",
		1: "FILEACTIONOPEN",
		2: "FILEACTIONCLOSE",
		3: "FILEACTIONDUP",
	}
	FileActionKind_value = map[string]int32{
		"FILEACTIONUNKNOWN": 0,
		"FILEACTIONOPEN":    1,
		"FILEACTIONCLOSE":   2,
		"FILEACTIONDUP":     3,
	}
)

func (x FileActionKind) Enum() *FileActionKind {
	p := new(FileActionKind)
	*p = x
	return p
}

func (x FileActionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileActionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_runner_runner_proto_enumTypes[1].Descriptor()
}

func (FileActionKind) Type() protoreflect.EnumType {
	return &file_runner_runner_proto_enumTypes[1]
}

func (x FileActionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileActionKind.Descriptor instead.
func (FileActionKind) EnumDescriptor() ([]byte, []int) {
	return file_runner_runner_proto_rawDescGZIP(), []int{1}
}

type Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_runner_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_runner_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_runner_runner_proto_rawDescGZIP(), []int{0}
}

func (x *Process) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ForkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkRequest) Reset() {
	*x = ForkRequest{}
	mi := &file_runner_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkRequest) ProtoMessage() {}

func (x *ForkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkRequest.ProtoReflect.Descriptor instead.
func (*ForkRequest) Descriptor() ([]byte, []int) {
	return file_runner_runner_proto_rawDescGZIP(), []int{1}
}

type FileAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          FileActionKind         `protobuf:"varint,1,opt,name=kind,proto3,enum=runner.FileActionKind" json:"kind,omitempty"`
	Fd            int32                  `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAction) Reset() {
	*x = FileAction{}
	mi := &file_runner_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAction) ProtoMessage() {}

func (x *FileAction) ProtoReflect() protoreflect.Message {
	mi := &file_runner_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAction.ProtoReflect.Descriptor instead.
func (*FileAction) Descriptor() ([]byte, []int) {
	return file_runner_runner_proto_rawDescGZIP(), []int{2}
}

func (x *FileAction) GetKind() FileActionKind {
	if x != nil {
		return x.Kind
	}
	return FileActionKind_FILEACTIONUNKNOWN
}

func (x *FileAction) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

type SpawnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Flags         []PosixSpawnFlag       `protobuf:"varint,2,rep,packed,name=flags,proto3,enum=runner.PosixSpawnFlag" json:"flags,omitempty"`
	Actions       []*FileAction          `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnRequest) Reset() {
	*x = SpawnRequest{}
	mi := &file_runner_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnRequest) ProtoMessage() {}

func (x *SpawnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnRequest.ProtoReflect.Descriptor instead.
func (*SpawnRequest) Descriptor() ([]byte, []int) {
	return file_runner_runner_proto_rawDescGZIP(), []int{3}
}

func (x *SpawnRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SpawnRequest) GetFlags() []PosixSpawnFlag {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *SpawnRequest) GetActions() []*FileAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *SpawnRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *SpawnRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type StopRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProcessId string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// Whether to force kill (SIGKILL vs SIGTERM)
	Force bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	// Timeout in seconds before force kill
	TimeoutSeconds int32 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_runner_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_runner_runner_proto_rawDescGZIP(), []int{4}
}

func (x *StopRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *StopRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *StopRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_runner_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_runner_runner_proto_rawDescGZIP(), []int{5}
}

func (x *StopResponse) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_runner_runner_proto protoreflect.FileDescriptor

const file_runner_runner_proto_rawDesc = "" +
	"\n" +
	"\x13runner/runner.proto\x12\x06runner\"\x1b\n" +
	"\aProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"\r\n" +
	"\vForkRequest\"H\n" +
	"\n" +
	"FileAction\x12*\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x16.runner.FileActionKindR\x04kind\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x05R\x02fd\"\xfb\x01\n" +
	"\fSpawnRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12,\n" +
	"\x05flags\x18\x02 \x03(\x0e2\x16.runner.PosixSpawnFlagR\x05flags\x12,\n" +
	"\aactions\x18\x03 \x03(\v2\x12.runner.FileActionR\aactions\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12/\n" +
	"\x03env\x18\x05 \x03(\v2\x1d.runner.SpawnRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\vStopRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"d\n" +
	"\fStopResponse\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode*)\n" +
	"\x0ePosixSpawnFlag\x12\x17\n" +
	"\x13POSIX_SPAWN_UNKNOWN\x10\x00*c\n" +
	"\x0eFileActionKind\x12\x15\n" +
	"\x11FILEACTIONUNKNOWN\x10\x00\x12\x12\n" +
	"\x0eFILEACTIONOPEN\x10\x01\x12\x13\n" +
	"\x0fFILEACTIONCLOSE\x10\x02\x12\x11\n" +
	"\rFILEACTIONDUP\x10\x032\x99\x01\n" +
	"\x06Runner\x12,\n" +
	"\x04Fork\x12\x13.runner.ForkRequest\x1a\x0f.runner.Process\x12.\n" +
	"\x05Spawn\x12\x14.runner.SpawnRequest\x1a\x0f.runner.Process\x121\n" +
	"\x04Stop\x12\x13.runner.StopRequest\x1a\x14.runner.StopResponseB&Z$github.com/accretional/runrpc/runnerb\x06proto3"

var (
	file_runner_runner_proto_rawDescOnce sync.Once
	file_runner_runner_proto_rawDescData []byte
)

func file_runner_runner_proto_rawDescGZIP() []byte {
	file_runner_runner_proto_rawDescOnce.Do(func() {
		file_runner_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_runner_proto_rawDesc), len(file_runner_runner_proto_rawDesc)))
	})
	return file_runner_runner_proto_rawDescData
}

var file_runner_runner_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_runner_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_runner_runner_proto_goTypes = []any{
	(PosixSpawnFlag)(0),  // 0: runner.PosixSpawnFlag
	(FileActionKind)(0),  // 1: runner.FileActionKind
	(*Process)(nil),      // 2: runner.Process
	(*ForkRequest)(nil),  // 3: runner.ForkRequest
	(*FileAction)(nil),   // 4: runner.FileAction
	(*SpawnRequest)(nil), // 5: runner.SpawnRequest
	(*StopRequest)(nil),  // 6: runner.StopRequest
	(*StopResponse)(nil), // 7: runner.StopResponse
	nil,                  // 8: runner.SpawnRequest.EnvEntry
}
var file_runner_runner_proto_depIdxs = []int32{
	1, // 0: runner.FileAction.kind:type_name -> runner.FileActionKind
	0, // 1: runner.SpawnRequest.flags:type_name -> runner.PosixSpawnFlag
	4, // 2: runner.SpawnRequest.actions:type_name -> runner.FileAction
	8, // 3: runner.SpawnRequest.env:type_name -> runner.SpawnRequest.EnvEntry
	3, // 4: runner.Runner.Fork:input_type -> runner.ForkRequest
	5, // 5: runner.Runner.Spawn:input_type -> runner.SpawnRequest
	6, // 6: runner.Runner.Stop:input_type -> runner.StopRequest
	2, // 7: runner.Runner.Fork:output_type -> runner.Process
	2, // 8: runner.Runner.Spawn:output_type -> runner.Process
	7, // 9: runner.Runner.Stop:output_type -> runner.StopResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_runner_runner_proto_init() }
func file_runner_runner_proto_init() {
	if File_runner_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_runner_proto_rawDesc), len(file_runner_runner_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runner_runner_proto_goTypes,
		DependencyIndexes: file_runner_runner_proto_depIdxs,
		EnumInfos:         file_runner_runner_proto_enumTypes,
		MessageInfos:      file_runner_runner_proto_msgTypes,
	}.Build()
	File_runner_runner_proto = out.File
	file_runner_runner_proto_goTypes = nil
	file_runner_runner_proto_depIdxs = nil
}
