// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: runner/runner.proto

package runner

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Runner_Batch_FullMethodName          = "/runner.Runner/Batch"
	Runner_Babble_FullMethodName         = "/runner.Runner/Babble"
	Runner_AppendAndPrint_FullMethodName = "/runner.Runner/AppendAndPrint"
	Runner_AddNewLine_FullMethodName     = "/runner.Runner/AddNewLine"
	Runner_Fork_FullMethodName           = "/runner.Runner/Fork"
	Runner_Spawn_FullMethodName          = "/runner.Runner/Spawn"
	Runner_Stop_FullMethodName           = "/runner.Runner/Stop"
)

// RunnerClient is the client API for Runner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Runner service handles execution of binaries as subprocesses
type RunnerClient interface {
	// Fork once for each member of the pipeline, create an intermediate pipe to buffer processing to the child and remove one method and set the child's input path to the pipe. Once child is created and setup (and connected to), start reading from input_path into MethodDescriptorProto until consumed
	Batch(ctx context.Context, in *Pipe, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// given a string eg "What I learned in boating school is" create 50 permutations of the words
	Babble(ctx context.Context, in *StringValue, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StringValue], error)
	// add a random char to the end
	AppendAndPrint(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StringValue, StringValue], error)
	AddNewLine(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StringValue, StringValue], error)
	// Fork forks the current process into a duplicate new process
	Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*Process, error)
	// Spawn implements Posix Spawn https://man7.org/linux/man-pages/man3/posix_spawn.3.html
	Spawn(ctx context.Context, in *SpawnRequest, opts ...grpc.CallOption) (*Process, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type runnerClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerClient(cc grpc.ClientConnInterface) RunnerClient {
	return &runnerClient{cc}
}

func (c *runnerClient) Batch(ctx context.Context, in *Pipe, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Runner_Batch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) Babble(ctx context.Context, in *StringValue, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StringValue], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runner_ServiceDesc.Streams[0], Runner_Babble_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StringValue, StringValue]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_BabbleClient = grpc.ServerStreamingClient[StringValue]

func (c *runnerClient) AppendAndPrint(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StringValue, StringValue], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runner_ServiceDesc.Streams[1], Runner_AppendAndPrint_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StringValue, StringValue]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_AppendAndPrintClient = grpc.BidiStreamingClient[StringValue, StringValue]

func (c *runnerClient) AddNewLine(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StringValue, StringValue], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runner_ServiceDesc.Streams[2], Runner_AddNewLine_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StringValue, StringValue]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_AddNewLineClient = grpc.ClientStreamingClient[StringValue, StringValue]

func (c *runnerClient) Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*Process, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Process)
	err := c.cc.Invoke(ctx, Runner_Fork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) Spawn(ctx context.Context, in *SpawnRequest, opts ...grpc.CallOption) (*Process, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Process)
	err := c.cc.Invoke(ctx, Runner_Spawn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, Runner_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerServer is the server API for Runner service.
// All implementations must embed UnimplementedRunnerServer
// for forward compatibility.
//
// Runner service handles execution of binaries as subprocesses
type RunnerServer interface {
	// Fork once for each member of the pipeline, create an intermediate pipe to buffer processing to the child and remove one method and set the child's input path to the pipe. Once child is created and setup (and connected to), start reading from input_path into MethodDescriptorProto until consumed
	Batch(context.Context, *Pipe) (*emptypb.Empty, error)
	// given a string eg "What I learned in boating school is" create 50 permutations of the words
	Babble(*StringValue, grpc.ServerStreamingServer[StringValue]) error
	// add a random char to the end
	AppendAndPrint(grpc.BidiStreamingServer[StringValue, StringValue]) error
	AddNewLine(grpc.ClientStreamingServer[StringValue, StringValue]) error
	// Fork forks the current process into a duplicate new process
	Fork(context.Context, *ForkRequest) (*Process, error)
	// Spawn implements Posix Spawn https://man7.org/linux/man-pages/man3/posix_spawn.3.html
	Spawn(context.Context, *SpawnRequest) (*Process, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedRunnerServer()
}

// UnimplementedRunnerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerServer struct{}

func (UnimplementedRunnerServer) Batch(context.Context, *Pipe) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Batch not implemented")
}
func (UnimplementedRunnerServer) Babble(*StringValue, grpc.ServerStreamingServer[StringValue]) error {
	return status.Errorf(codes.Unimplemented, "method Babble not implemented")
}
func (UnimplementedRunnerServer) AppendAndPrint(grpc.BidiStreamingServer[StringValue, StringValue]) error {
	return status.Errorf(codes.Unimplemented, "method AppendAndPrint not implemented")
}
func (UnimplementedRunnerServer) AddNewLine(grpc.ClientStreamingServer[StringValue, StringValue]) error {
	return status.Errorf(codes.Unimplemented, "method AddNewLine not implemented")
}
func (UnimplementedRunnerServer) Fork(context.Context, *ForkRequest) (*Process, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fork not implemented")
}
func (UnimplementedRunnerServer) Spawn(context.Context, *SpawnRequest) (*Process, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Spawn not implemented")
}
func (UnimplementedRunnerServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedRunnerServer) mustEmbedUnimplementedRunnerServer() {}
func (UnimplementedRunnerServer) testEmbeddedByValue()                {}

// UnsafeRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerServer will
// result in compilation errors.
type UnsafeRunnerServer interface {
	mustEmbedUnimplementedRunnerServer()
}

func RegisterRunnerServer(s grpc.ServiceRegistrar, srv RunnerServer) {
	// If the following call pancis, it indicates UnimplementedRunnerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Runner_ServiceDesc, srv)
}

func _Runner_Batch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pipe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).Batch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_Batch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).Batch(ctx, req.(*Pipe))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_Babble_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StringValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServer).Babble(m, &grpc.GenericServerStream[StringValue, StringValue]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_BabbleServer = grpc.ServerStreamingServer[StringValue]

func _Runner_AppendAndPrint_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RunnerServer).AppendAndPrint(&grpc.GenericServerStream[StringValue, StringValue]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_AppendAndPrintServer = grpc.BidiStreamingServer[StringValue, StringValue]

func _Runner_AddNewLine_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RunnerServer).AddNewLine(&grpc.GenericServerStream[StringValue, StringValue]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_AddNewLineServer = grpc.ClientStreamingServer[StringValue, StringValue]

func _Runner_Fork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).Fork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_Fork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).Fork(ctx, req.(*ForkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_Spawn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).Spawn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_Spawn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).Spawn(ctx, req.(*SpawnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Runner_ServiceDesc is the grpc.ServiceDesc for Runner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runner.Runner",
	HandlerType: (*RunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Batch",
			Handler:    _Runner_Batch_Handler,
		},
		{
			MethodName: "Fork",
			Handler:    _Runner_Fork_Handler,
		},
		{
			MethodName: "Spawn",
			Handler:    _Runner_Spawn_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Runner_Stop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Babble",
			Handler:       _Runner_Babble_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AppendAndPrint",
			Handler:       _Runner_AppendAndPrint_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AddNewLine",
			Handler:       _Runner_AddNewLine_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "runner/runner.proto",
}
