// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: filer/plan92.proto

package filer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Plan92_Get_FullMethodName          = "/filer.Plan92/Get"
	Plan92_OpenSession_FullMethodName  = "/filer.Plan92/OpenSession"
	Plan92_CloseSession_FullMethodName = "/filer.Plan92/CloseSession"
	Plan92_Read_FullMethodName         = "/filer.Plan92/Read"
	Plan92_Download_FullMethodName     = "/filer.Plan92/Download"
	Plan92_Write_FullMethodName        = "/filer.Plan92/Write"
	Plan92_Upload_FullMethodName       = "/filer.Plan92/Upload"
)

// Plan92Client is the client API for Plan92 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Plan92 is a Plan9-like filesystem service providing file I/O operations over gRPC.
// It supports Open, Read, Write, Close operations with session-based FD management
// and hierarchical permission checking.
type Plan92Client interface {
	// Data from public resources can be provided through this uncredentialed endpoint; these will generally be static or shared across the instance if dynamic.
	Get(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*Data, error)
	// Open Sessions become user-scoped, consumable gRPC streams accessed with an id (corresponding to an fd) persistent for the life of the stream.
	// The stream name provided when initializing that stream is synchronously invalidated; if the stream is disrupted or the user wishes to reconnect, they need to request a new secret for it.
	OpenSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Session, error)
	CloseSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Data, error)
	// Read the upstream resource (note a resource can contain multiple resources or be too big to serialize as a stream message)
	Read(ctx context.Context, in *Session, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Data], error)
	// Download the upstream resources. First resource must be a Session
	Download(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Resource, Data], error)
	// First Data must be a Session, then Data
	Write(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Data, Resource], error)
	// Upload the upstream resources. First Data must be a Session, then resources followed by their data
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Data, Resource], error)
}

type plan92Client struct {
	cc grpc.ClientConnInterface
}

func NewPlan92Client(cc grpc.ClientConnInterface) Plan92Client {
	return &plan92Client{cc}
}

func (c *plan92Client) Get(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*Data, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Data)
	err := c.cc.Invoke(ctx, Plan92_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plan92Client) OpenSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Plan92_OpenSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plan92Client) CloseSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Data, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Data)
	err := c.cc.Invoke(ctx, Plan92_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plan92Client) Read(ctx context.Context, in *Session, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Data], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Plan92_ServiceDesc.Streams[0], Plan92_Read_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Session, Data]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plan92_ReadClient = grpc.ServerStreamingClient[Data]

func (c *plan92Client) Download(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Resource, Data], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Plan92_ServiceDesc.Streams[1], Plan92_Download_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Resource, Data]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plan92_DownloadClient = grpc.BidiStreamingClient[Resource, Data]

func (c *plan92Client) Write(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Data, Resource], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Plan92_ServiceDesc.Streams[2], Plan92_Write_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Data, Resource]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plan92_WriteClient = grpc.ClientStreamingClient[Data, Resource]

func (c *plan92Client) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Data, Resource], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Plan92_ServiceDesc.Streams[3], Plan92_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Data, Resource]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plan92_UploadClient = grpc.BidiStreamingClient[Data, Resource]

// Plan92Server is the server API for Plan92 service.
// All implementations must embed UnimplementedPlan92Server
// for forward compatibility.
//
// Plan92 is a Plan9-like filesystem service providing file I/O operations over gRPC.
// It supports Open, Read, Write, Close operations with session-based FD management
// and hierarchical permission checking.
type Plan92Server interface {
	// Data from public resources can be provided through this uncredentialed endpoint; these will generally be static or shared across the instance if dynamic.
	Get(context.Context, *Resource) (*Data, error)
	// Open Sessions become user-scoped, consumable gRPC streams accessed with an id (corresponding to an fd) persistent for the life of the stream.
	// The stream name provided when initializing that stream is synchronously invalidated; if the stream is disrupted or the user wishes to reconnect, they need to request a new secret for it.
	OpenSession(context.Context, *Session) (*Session, error)
	CloseSession(context.Context, *Session) (*Data, error)
	// Read the upstream resource (note a resource can contain multiple resources or be too big to serialize as a stream message)
	Read(*Session, grpc.ServerStreamingServer[Data]) error
	// Download the upstream resources. First resource must be a Session
	Download(grpc.BidiStreamingServer[Resource, Data]) error
	// First Data must be a Session, then Data
	Write(grpc.ClientStreamingServer[Data, Resource]) error
	// Upload the upstream resources. First Data must be a Session, then resources followed by their data
	Upload(grpc.BidiStreamingServer[Data, Resource]) error
	mustEmbedUnimplementedPlan92Server()
}

// UnimplementedPlan92Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlan92Server struct{}

func (UnimplementedPlan92Server) Get(context.Context, *Resource) (*Data, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPlan92Server) OpenSession(context.Context, *Session) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedPlan92Server) CloseSession(context.Context, *Session) (*Data, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedPlan92Server) Read(*Session, grpc.ServerStreamingServer[Data]) error {
	return status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedPlan92Server) Download(grpc.BidiStreamingServer[Resource, Data]) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedPlan92Server) Write(grpc.ClientStreamingServer[Data, Resource]) error {
	return status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedPlan92Server) Upload(grpc.BidiStreamingServer[Data, Resource]) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedPlan92Server) mustEmbedUnimplementedPlan92Server() {}
func (UnimplementedPlan92Server) testEmbeddedByValue()                {}

// UnsafePlan92Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Plan92Server will
// result in compilation errors.
type UnsafePlan92Server interface {
	mustEmbedUnimplementedPlan92Server()
}

func RegisterPlan92Server(s grpc.ServiceRegistrar, srv Plan92Server) {
	// If the following call pancis, it indicates UnimplementedPlan92Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Plan92_ServiceDesc, srv)
}

func _Plan92_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Plan92Server).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plan92_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Plan92Server).Get(ctx, req.(*Resource))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plan92_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Plan92Server).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plan92_OpenSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Plan92Server).OpenSession(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plan92_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Plan92Server).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plan92_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Plan92Server).CloseSession(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plan92_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Session)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(Plan92Server).Read(m, &grpc.GenericServerStream[Session, Data]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plan92_ReadServer = grpc.ServerStreamingServer[Data]

func _Plan92_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Plan92Server).Download(&grpc.GenericServerStream[Resource, Data]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plan92_DownloadServer = grpc.BidiStreamingServer[Resource, Data]

func _Plan92_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Plan92Server).Write(&grpc.GenericServerStream[Data, Resource]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plan92_WriteServer = grpc.ClientStreamingServer[Data, Resource]

func _Plan92_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Plan92Server).Upload(&grpc.GenericServerStream[Data, Resource]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plan92_UploadServer = grpc.BidiStreamingServer[Data, Resource]

// Plan92_ServiceDesc is the grpc.ServiceDesc for Plan92 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plan92_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filer.Plan92",
	HandlerType: (*Plan92Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Plan92_Get_Handler,
		},
		{
			MethodName: "OpenSession",
			Handler:    _Plan92_OpenSession_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _Plan92_CloseSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Read",
			Handler:       _Plan92_Read_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _Plan92_Download_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Write",
			Handler:       _Plan92_Write_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Upload",
			Handler:       _Plan92_Upload_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "filer/plan92.proto",
}
