// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: filer/plan92.proto

package filer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpenMode specifies the authorized interactions within the scope of an open session
type OpenMode int32

const (
	OpenMode_OPEN_MODE_UNKNOWN OpenMode = 0
	OpenMode_READ              OpenMode = 1 // OREAD - open for reading
	OpenMode_WRITE             OpenMode = 2 // OWRITE - open for writing
	OpenMode_EXEC              OpenMode = 3 // OEXEC - open for execution
	OpenMode_WTRUNC            OpenMode = 4 // OTRUNC - truncate file on open, ie rewrite/set it
	OpenMode_RCLOSE            OpenMode = 5 // ORCLOSE - remove file on close, ie it only exists within this session
)

// Enum value maps for OpenMode.
var (
	OpenMode_name = map[int32]string{
		0: "OPEN_MODE_UNKNOWN",
		1: "READ",
		2: "WRITE",
		3: "EXEC",
		4: "WTRUNC",
		5: "RCLOSE",
	}
	OpenMode_value = map[string]int32{
		"OPEN_MODE_UNKNOWN": 0,
		"READ":              1,
		"WRITE":             2,
		"EXEC":              3,
		"WTRUNC":            4,
		"RCLOSE":            5,
	}
)

func (x OpenMode) Enum() *OpenMode {
	p := new(OpenMode)
	*p = x
	return p
}

func (x OpenMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenMode) Descriptor() protoreflect.EnumDescriptor {
	return file_filer_plan92_proto_enumTypes[0].Descriptor()
}

func (OpenMode) Type() protoreflect.EnumType {
	return &file_filer_plan92_proto_enumTypes[0]
}

func (x OpenMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenMode.Descriptor instead.
func (OpenMode) EnumDescriptor() ([]byte, []int) {
	return file_filer_plan92_proto_rawDescGZIP(), []int{0}
}

type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encodes a token with name=<secret> and owners=<provenance> stemming from the user's Identity they used to Authenticate with via the Identifier
	User *Resource `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// id is persistent, name is consumed when Session is joined. User remains owner until session is joined, at which point it reverts to the system.
	Upstream *Resource `protobuf:"bytes,2,opt,name=upstream,proto3" json:"upstream,omitempty"`
	// Since a user could open additional sessions within the scope of an active session, they may need to be aborted, cleaned up, or persisted.
	Downstream    []*Session `protobuf:"bytes,3,rep,name=downstream,proto3" json:"downstream,omitempty"`
	Omode         OpenMode   `protobuf:"varint,4,opt,name=omode,proto3,enum=filer.OpenMode" json:"omode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_filer_plan92_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_filer_plan92_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_filer_plan92_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetUser() *Resource {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Session) GetUpstream() *Resource {
	if x != nil {
		return x.Upstream
	}
	return nil
}

func (x *Session) GetDownstream() []*Session {
	if x != nil {
		return x.Downstream
	}
	return nil
}

func (x *Session) GetOmode() OpenMode {
	if x != nil {
		return x.Omode
	}
	return OpenMode_OPEN_MODE_UNKNOWN
}

// "Files" are a confusing name to many users since they're generally assumed to be static content hosted on a file system. So, our "files" are called Resources, and Resources have a numeric "id" like an fd.
// Resources mainly differ from traditional fd-based files in that their ids are persistent, they are typed if possible, and they may be handled in a distributed environment or database rather than a regular filesystem.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// May correspond to a system resource or upstream Session.
	Owners []*Resource `protobuf:"bytes,3,rep,name=owners,proto3" json:"owners,omitempty"`
	// URI that resolves to a FileDescriptorProto for the Resource.
	Type          string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_filer_plan92_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_filer_plan92_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_filer_plan92_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetOwners() []*Resource {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Note that since Resource is a Message, an instance of Data can be a Resource, and every Resource can become Data.
type Data struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Descriptor_   *descriptorpb.DescriptorProto `protobuf:"bytes,1,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	Value         []byte                        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_filer_plan92_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_filer_plan92_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_filer_plan92_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDescriptor_() *descriptorpb.DescriptorProto {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *Data) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_filer_plan92_proto protoreflect.FileDescriptor

const file_filer_plan92_proto_rawDesc = "" +
	"\n" +
	"\x12filer/plan92.proto\x12\x05filer\x1a google/protobuf/descriptor.proto\"\xb2\x01\n" +
	"\aSession\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.filer.ResourceR\x04user\x12+\n" +
	"\bupstream\x18\x02 \x01(\v2\x0f.filer.ResourceR\bupstream\x12.\n" +
	"\n" +
	"downstream\x18\x03 \x03(\v2\x0e.filer.SessionR\n" +
	"downstream\x12%\n" +
	"\x05omode\x18\x04 \x01(\x0e2\x0f.filer.OpenModeR\x05omode\"k\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x06owners\x18\x03 \x03(\v2\x0f.filer.ResourceR\x06owners\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"^\n" +
	"\x04Data\x12@\n" +
	"\n" +
	"descriptor\x18\x01 \x01(\v2 .google.protobuf.DescriptorProtoR\n" +
	"descriptor\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value*X\n" +
	"\bOpenMode\x12\x15\n" +
	"\x11OPEN_MODE_UNKNOWN\x10\x00\x12\b\n" +
	"\x04READ\x10\x01\x12\t\n" +
	"\x05WRITE\x10\x02\x12\b\n" +
	"\x04EXEC\x10\x03\x12\n" +
	"\n" +
	"\x06WTRUNC\x10\x04\x12\n" +
	"\n" +
	"\x06RCLOSE\x10\x052\xb3\x02\n" +
	"\x06Plan92\x12#\n" +
	"\x03Get\x12\x0f.filer.Resource\x1a\v.filer.Data\x12-\n" +
	"\vOpenSession\x12\x0e.filer.Session\x1a\x0e.filer.Session\x12+\n" +
	"\fCloseSession\x12\x0e.filer.Session\x1a\v.filer.Data\x12%\n" +
	"\x04Read\x12\x0e.filer.Session\x1a\v.filer.Data0\x01\x12,\n" +
	"\bDownload\x12\x0f.filer.Resource\x1a\v.filer.Data(\x010\x01\x12'\n" +
	"\x05Write\x12\v.filer.Data\x1a\x0f.filer.Resource(\x01\x12*\n" +
	"\x06Upload\x12\v.filer.Data\x1a\x0f.filer.Resource(\x010\x01B%Z#github.com/accretional/runrpc/filerb\x06proto3"

var (
	file_filer_plan92_proto_rawDescOnce sync.Once
	file_filer_plan92_proto_rawDescData []byte
)

func file_filer_plan92_proto_rawDescGZIP() []byte {
	file_filer_plan92_proto_rawDescOnce.Do(func() {
		file_filer_plan92_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filer_plan92_proto_rawDesc), len(file_filer_plan92_proto_rawDesc)))
	})
	return file_filer_plan92_proto_rawDescData
}

var file_filer_plan92_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_filer_plan92_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_filer_plan92_proto_goTypes = []any{
	(OpenMode)(0),                        // 0: filer.OpenMode
	(*Session)(nil),                      // 1: filer.Session
	(*Resource)(nil),                     // 2: filer.Resource
	(*Data)(nil),                         // 3: filer.Data
	(*descriptorpb.DescriptorProto)(nil), // 4: google.protobuf.DescriptorProto
}
var file_filer_plan92_proto_depIdxs = []int32{
	2,  // 0: filer.Session.user:type_name -> filer.Resource
	2,  // 1: filer.Session.upstream:type_name -> filer.Resource
	1,  // 2: filer.Session.downstream:type_name -> filer.Session
	0,  // 3: filer.Session.omode:type_name -> filer.OpenMode
	2,  // 4: filer.Resource.owners:type_name -> filer.Resource
	4,  // 5: filer.Data.descriptor:type_name -> google.protobuf.DescriptorProto
	2,  // 6: filer.Plan92.Get:input_type -> filer.Resource
	1,  // 7: filer.Plan92.OpenSession:input_type -> filer.Session
	1,  // 8: filer.Plan92.CloseSession:input_type -> filer.Session
	1,  // 9: filer.Plan92.Read:input_type -> filer.Session
	2,  // 10: filer.Plan92.Download:input_type -> filer.Resource
	3,  // 11: filer.Plan92.Write:input_type -> filer.Data
	3,  // 12: filer.Plan92.Upload:input_type -> filer.Data
	3,  // 13: filer.Plan92.Get:output_type -> filer.Data
	1,  // 14: filer.Plan92.OpenSession:output_type -> filer.Session
	3,  // 15: filer.Plan92.CloseSession:output_type -> filer.Data
	3,  // 16: filer.Plan92.Read:output_type -> filer.Data
	3,  // 17: filer.Plan92.Download:output_type -> filer.Data
	2,  // 18: filer.Plan92.Write:output_type -> filer.Resource
	2,  // 19: filer.Plan92.Upload:output_type -> filer.Resource
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_filer_plan92_proto_init() }
func file_filer_plan92_proto_init() {
	if File_filer_plan92_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filer_plan92_proto_rawDesc), len(file_filer_plan92_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filer_plan92_proto_goTypes,
		DependencyIndexes: file_filer_plan92_proto_depIdxs,
		EnumInfos:         file_filer_plan92_proto_enumTypes,
		MessageInfos:      file_filer_plan92_proto_msgTypes,
	}.Build()
	File_filer_plan92_proto = out.File
	file_filer_plan92_proto_goTypes = nil
	file_filer_plan92_proto_depIdxs = nil
}
