// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: filer/storer.proto

package filer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Storage int32

const (
	Storage_STORAGE_UNKNOWN Storage = 0
	// eg encoded in the binary
	Storage_Immutable Storage = 1
	Storage_Memory    Storage = 2
	Storage_Block     Storage = 3
	Storage_Blob      Storage = 4
)

// Enum value maps for Storage.
var (
	Storage_name = map[int32]string{
		0: "STORAGE_UNKNOWN",
		1: "Immutable",
		2: "Memory",
		3: "Block",
		4: "Blob",
	}
	Storage_value = map[string]int32{
		"STORAGE_UNKNOWN": 0,
		"Immutable":       1,
		"Memory":          2,
		"Block":           3,
		"Blob":            4,
	}
)

func (x Storage) Enum() *Storage {
	p := new(Storage)
	*p = x
	return p
}

func (x Storage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Storage) Descriptor() protoreflect.EnumDescriptor {
	return file_filer_storer_proto_enumTypes[0].Descriptor()
}

func (Storage) Type() protoreflect.EnumType {
	return &file_filer_storer_proto_enumTypes[0]
}

func (x Storage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Storage.Descriptor instead.
func (Storage) EnumDescriptor() ([]byte, []int) {
	return file_filer_storer_proto_rawDescGZIP(), []int{0}
}

// File stores are encoded in a few formats
type StorageFormat int32

const (
	StorageFormat_STORAGE_FORMAT_UNKNOWN StorageFormat = 0
	StorageFormat_BinaryProto            StorageFormat = 1
	StorageFormat_TextProto              StorageFormat = 2
	// Single type, sequential starting from the end of the File [message] int64 message_len
	StorageFormat_Sequence StorageFormat = 3 // Later add gzip, etc
)

// Enum value maps for StorageFormat.
var (
	StorageFormat_name = map[int32]string{
		0: "STORAGE_FORMAT_UNKNOWN",
		1: "BinaryProto",
		2: "TextProto",
		3: "Sequence",
	}
	StorageFormat_value = map[string]int32{
		"STORAGE_FORMAT_UNKNOWN": 0,
		"BinaryProto":            1,
		"TextProto":              2,
		"Sequence":               3,
	}
)

func (x StorageFormat) Enum() *StorageFormat {
	p := new(StorageFormat)
	*p = x
	return p
}

func (x StorageFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_filer_storer_proto_enumTypes[1].Descriptor()
}

func (StorageFormat) Type() protoreflect.EnumType {
	return &file_filer_storer_proto_enumTypes[1]
}

func (x StorageFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageFormat.Descriptor instead.
func (StorageFormat) EnumDescriptor() ([]byte, []int) {
	return file_filer_storer_proto_rawDescGZIP(), []int{1}
}

type StoreAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Storage       Storage                `protobuf:"varint,2,opt,name=storage,proto3,enum=filer.Storage" json:"storage,omitempty"`
	Format        StorageFormat          `protobuf:"varint,3,opt,name=format,proto3,enum=filer.StorageFormat" json:"format,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreAddress) Reset() {
	*x = StoreAddress{}
	mi := &file_filer_storer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreAddress) ProtoMessage() {}

func (x *StoreAddress) ProtoReflect() protoreflect.Message {
	mi := &file_filer_storer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreAddress.ProtoReflect.Descriptor instead.
func (*StoreAddress) Descriptor() ([]byte, []int) {
	return file_filer_storer_proto_rawDescGZIP(), []int{0}
}

func (x *StoreAddress) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StoreAddress) GetStorage() Storage {
	if x != nil {
		return x.Storage
	}
	return Storage_STORAGE_UNKNOWN
}

func (x *StoreAddress) GetFormat() StorageFormat {
	if x != nil {
		return x.Format
	}
	return StorageFormat_STORAGE_FORMAT_UNKNOWN
}

func (x *StoreAddress) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ResourceDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Address       *StoreAddress          `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDefinition) Reset() {
	*x = ResourceDefinition{}
	mi := &file_filer_storer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDefinition) ProtoMessage() {}

func (x *ResourceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_filer_storer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDefinition.ProtoReflect.Descriptor instead.
func (*ResourceDefinition) Descriptor() ([]byte, []int) {
	return file_filer_storer_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceDefinition) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ResourceDefinition) GetAddress() *StoreAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ResourceDefinition) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_filer_storer_proto protoreflect.FileDescriptor

const file_filer_storer_proto_rawDesc = "" +
	"\n" +
	"\x12filer/storer.proto\x12\x05filer\x1a\x12filer/plan92.proto\"\x90\x01\n" +
	"\fStoreAddress\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12(\n" +
	"\astorage\x18\x02 \x01(\x0e2\x0e.filer.StorageR\astorage\x12,\n" +
	"\x06format\x18\x03 \x01(\x0e2\x14.filer.StorageFormatR\x06format\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"\x86\x01\n" +
	"\x12ResourceDefinition\x12+\n" +
	"\bresource\x18\x01 \x01(\v2\x0f.filer.ResourceR\bresource\x12-\n" +
	"\aaddress\x18\x02 \x01(\v2\x13.filer.StoreAddressR\aaddress\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value*N\n" +
	"\aStorage\x12\x13\n" +
	"\x0fSTORAGE_UNKNOWN\x10\x00\x12\r\n" +
	"\tImmutable\x10\x01\x12\n" +
	"\n" +
	"\x06Memory\x10\x02\x12\t\n" +
	"\x05Block\x10\x03\x12\b\n" +
	"\x04Blob\x10\x04*Y\n" +
	"\rStorageFormat\x12\x1a\n" +
	"\x16STORAGE_FORMAT_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vBinaryProto\x10\x01\x12\r\n" +
	"\tTextProto\x10\x02\x12\f\n" +
	"\bSequence\x10\x032\xeb\x01\n" +
	"\x06Storer\x127\n" +
	"\x05Store\x12\x19.filer.ResourceDefinition\x1a\x13.filer.StoreAddress\x12<\n" +
	"\x06Append\x12\x19.filer.ResourceDefinition\x1a\x13.filer.StoreAddress(\x010\x01\x122\n" +
	"\x04Load\x12\x0f.filer.Resource\x1a\x19.filer.ResourceDefinition\x126\n" +
	"\x04Read\x12\x0f.filer.Resource\x1a\x19.filer.ResourceDefinition(\x010\x01B%Z#github.com/accretional/runrpc/filerb\x06proto3"

var (
	file_filer_storer_proto_rawDescOnce sync.Once
	file_filer_storer_proto_rawDescData []byte
)

func file_filer_storer_proto_rawDescGZIP() []byte {
	file_filer_storer_proto_rawDescOnce.Do(func() {
		file_filer_storer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filer_storer_proto_rawDesc), len(file_filer_storer_proto_rawDesc)))
	})
	return file_filer_storer_proto_rawDescData
}

var file_filer_storer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_filer_storer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_filer_storer_proto_goTypes = []any{
	(Storage)(0),               // 0: filer.Storage
	(StorageFormat)(0),         // 1: filer.StorageFormat
	(*StoreAddress)(nil),       // 2: filer.StoreAddress
	(*ResourceDefinition)(nil), // 3: filer.ResourceDefinition
	(*Resource)(nil),           // 4: filer.Resource
}
var file_filer_storer_proto_depIdxs = []int32{
	0, // 0: filer.StoreAddress.storage:type_name -> filer.Storage
	1, // 1: filer.StoreAddress.format:type_name -> filer.StorageFormat
	4, // 2: filer.ResourceDefinition.resource:type_name -> filer.Resource
	2, // 3: filer.ResourceDefinition.address:type_name -> filer.StoreAddress
	3, // 4: filer.Storer.Store:input_type -> filer.ResourceDefinition
	3, // 5: filer.Storer.Append:input_type -> filer.ResourceDefinition
	4, // 6: filer.Storer.Load:input_type -> filer.Resource
	4, // 7: filer.Storer.Read:input_type -> filer.Resource
	2, // 8: filer.Storer.Store:output_type -> filer.StoreAddress
	2, // 9: filer.Storer.Append:output_type -> filer.StoreAddress
	3, // 10: filer.Storer.Load:output_type -> filer.ResourceDefinition
	3, // 11: filer.Storer.Read:output_type -> filer.ResourceDefinition
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_filer_storer_proto_init() }
func file_filer_storer_proto_init() {
	if File_filer_storer_proto != nil {
		return
	}
	file_filer_plan92_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filer_storer_proto_rawDesc), len(file_filer_storer_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filer_storer_proto_goTypes,
		DependencyIndexes: file_filer_storer_proto_depIdxs,
		EnumInfos:         file_filer_storer_proto_enumTypes,
		MessageInfos:      file_filer_storer_proto_msgTypes,
	}.Build()
	File_filer_storer_proto = out.File
	file_filer_storer_proto_goTypes = nil
	file_filer_storer_proto_depIdxs = nil
}
