// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: filer/storer.proto

package filer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Storer_Store_FullMethodName  = "/filer.Storer/Store"
	Storer_Append_FullMethodName = "/filer.Storer/Append"
	Storer_Load_FullMethodName   = "/filer.Storer/Load"
	Storer_Read_FullMethodName   = "/filer.Storer/Read"
)

// StorerClient is the client API for Storer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorerClient interface {
	Store(ctx context.Context, in *ResourceDefinition, opts ...grpc.CallOption) (*StoreAddress, error)
	Append(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ResourceDefinition, StoreAddress], error)
	Load(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*ResourceDefinition, error)
	Read(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Resource, ResourceDefinition], error)
}

type storerClient struct {
	cc grpc.ClientConnInterface
}

func NewStorerClient(cc grpc.ClientConnInterface) StorerClient {
	return &storerClient{cc}
}

func (c *storerClient) Store(ctx context.Context, in *ResourceDefinition, opts ...grpc.CallOption) (*StoreAddress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreAddress)
	err := c.cc.Invoke(ctx, Storer_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storerClient) Append(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ResourceDefinition, StoreAddress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Storer_ServiceDesc.Streams[0], Storer_Append_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResourceDefinition, StoreAddress]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Storer_AppendClient = grpc.BidiStreamingClient[ResourceDefinition, StoreAddress]

func (c *storerClient) Load(ctx context.Context, in *Resource, opts ...grpc.CallOption) (*ResourceDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceDefinition)
	err := c.cc.Invoke(ctx, Storer_Load_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storerClient) Read(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Resource, ResourceDefinition], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Storer_ServiceDesc.Streams[1], Storer_Read_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Resource, ResourceDefinition]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Storer_ReadClient = grpc.BidiStreamingClient[Resource, ResourceDefinition]

// StorerServer is the server API for Storer service.
// All implementations must embed UnimplementedStorerServer
// for forward compatibility.
type StorerServer interface {
	Store(context.Context, *ResourceDefinition) (*StoreAddress, error)
	Append(grpc.BidiStreamingServer[ResourceDefinition, StoreAddress]) error
	Load(context.Context, *Resource) (*ResourceDefinition, error)
	Read(grpc.BidiStreamingServer[Resource, ResourceDefinition]) error
	mustEmbedUnimplementedStorerServer()
}

// UnimplementedStorerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorerServer struct{}

func (UnimplementedStorerServer) Store(context.Context, *ResourceDefinition) (*StoreAddress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedStorerServer) Append(grpc.BidiStreamingServer[ResourceDefinition, StoreAddress]) error {
	return status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedStorerServer) Load(context.Context, *Resource) (*ResourceDefinition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (UnimplementedStorerServer) Read(grpc.BidiStreamingServer[Resource, ResourceDefinition]) error {
	return status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedStorerServer) mustEmbedUnimplementedStorerServer() {}
func (UnimplementedStorerServer) testEmbeddedByValue()                {}

// UnsafeStorerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorerServer will
// result in compilation errors.
type UnsafeStorerServer interface {
	mustEmbedUnimplementedStorerServer()
}

func RegisterStorerServer(s grpc.ServiceRegistrar, srv StorerServer) {
	// If the following call pancis, it indicates UnimplementedStorerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Storer_ServiceDesc, srv)
}

func _Storer_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceDefinition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorerServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storer_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorerServer).Store(ctx, req.(*ResourceDefinition))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storer_Append_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorerServer).Append(&grpc.GenericServerStream[ResourceDefinition, StoreAddress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Storer_AppendServer = grpc.BidiStreamingServer[ResourceDefinition, StoreAddress]

func _Storer_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorerServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Storer_Load_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorerServer).Load(ctx, req.(*Resource))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storer_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorerServer).Read(&grpc.GenericServerStream[Resource, ResourceDefinition]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Storer_ReadServer = grpc.BidiStreamingServer[Resource, ResourceDefinition]

// Storer_ServiceDesc is the grpc.ServiceDesc for Storer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Storer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filer.Storer",
	HandlerType: (*StorerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _Storer_Store_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _Storer_Load_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Append",
			Handler:       _Storer_Append_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Read",
			Handler:       _Storer_Read_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "filer/storer.proto",
}
